### ISSUE TITLE
Update for phpBB 3.2

### ISSUE THREAD

**Issue by avandenberghe** [bbDKP/style-PBTech#2]

**Comment by Kattienika** [comment]
Hello, you are working on update?

**Comment by TWEagle** [comment]
Yes I also like this theme

**Comment by avandenberghe** [comment]
code changes prosilver_changes_3.1.10-3.2.0.diff 
https://gist.github.com/hanakin/38025ffb267b238c259b0f51400ef788

**Comment by avandenberghe** [comment]
finalised
